project_id = "lgyapmkpkumydtufsmne"

[functions.airtable-proxy]
verify_jwt = true

[functions.user-admin]
verify_jwt = true

[functions.import-customers]
verify_jwt = true

[functions.fix-phone-numbers]
verify_jwt = true
