// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgyapmkpkumydtufsmne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxneWFwbWtwa3VteWR0dWZzbW5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDY0MjcsImV4cCI6MjA3MDEyMjQyN30.xQYtM4oKqmuEV_4mvNMhoSrZzLwQmz2Z34MW6x2XtjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});